
server:
  port: 9001
  servlet:
    context-path: /core
mybatis-plus:
  mapper-locations: classpath:com/example/jhb/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jhb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: jhb1011@
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

swagger:
  username: admin
  password: admin


